In [2]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import os  # Import the os module

# Define the path to the datasets
folder_path = r"C:\Users\ADMIN\Desktop\Cyclist_data"

all_files = os.listdir(folder_path)  # Corrected function name to listdir

data_frames = []

for filename in all_files:
    file_path = os.path.join(folder_path, filename)  # Create the full path for each file
    df = pd.read_csv(file_path)  # Read each CSV file
    data_frames.append(df)  # Add the DataFrame to the list

all_data = pd.concat(data_frames, ignore_index=True)  # Concatenate all DataFrames

In [6]:
for col in ['rideable_type', 'rideable_type' , 'started_at' , 'ended_at' ,'start_station_name', 'start_station_id', 
            'end_station_name', 'end_station_id', 'member_casual']:
    all_data[col] = all_data[col].astype('category')

print(all_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24828293 entries, 0 to 24828292
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       category
 2   started_at          category
 3   ended_at            category
 4   start_station_name  category
 5   start_station_id    category
 6   end_station_name    category
 7   end_station_id      category
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       category
dtypes: category(8), float64(4), object(1)
memory usage: 2.7+ GB
None

In [8]:
print(all_data)

                   ride_id     rideable_type               started_at  \
0         A847FADBBC638E45       docked_bike      2020-04-26 17:45:14
1         5405B80E996FF60D       docked_bike      2020-04-17 17:08:54
2         5DD24A79A4E006F4       docked_bike      2020-04-01 17:54:13
3         2A59BBDF5CDBA725       docked_bike      2020-04-07 12:50:19
4         27AD306C119C6158       docked_bike      2020-04-18 10:22:59
...                    ...               ...                      ...
24828288  97CC940225245B6C  electric_scooter  2024-09-26 12:09:15.215
24828289  4F8F2383056480E0     electric_bike  2024-09-10 18:10:44.046
24828290  6A60FA5CF71D36E6     electric_bike  2024-09-14 10:52:22.777
24828291  F257ABC8B92ED5E5     electric_bike  2024-09-30 10:52:18.714
24828292  781862ED31812AE7     electric_bike  2024-09-20 22:49:21.914

                         ended_at             start_station_name  \
0             2020-04-26 18:12:03                   Eckhart Park
1             2020-04-17 17:17:03      Drake Ave & Fullerton Ave
2             2020-04-01 18:08:36           McClurg Ct & Erie St
3             2020-04-07 13:02:31   California Ave & Division St
4             2020-04-18 11:15:54           Rush St & Hubbard St
...                           ...                            ...
24828288  2024-09-26 12:18:48.191  Franklin St & Adams St (Temp)
24828289  2024-09-10 18:21:54.463        Streeter Dr & Grand Ave
24828290  2024-09-14 11:03:36.081      Halsted St & Clybourn Ave
24828291  2024-09-30 11:31:46.032        Streeter Dr & Grand Ave
24828292  2024-09-20 23:37:15.731      Halsted St & Clybourn Ave

         start_station_id             end_station_name end_station_id  \
0                      86  Lincoln Ave & Diversey Pkwy          152.0
1                     503              Kosciuszko Park          499.0
2                     142   Indiana Ave & Roosevelt Rd          255.0
3                     216       Wood St & Augusta Blvd          657.0
4                     125   Sheridan Rd & Lawrence Ave          323.0
...                   ...                          ...            ...
24828288     TA1309000008                          NaN            NaN
24828289            13022                          NaN            NaN
24828290              331                          NaN            NaN
24828291            13022                          NaN            NaN
24828292              331                          NaN            NaN

          start_lat  start_lng  end_lat  end_lng member_casual
0         41.896400 -87.661000  41.9322 -87.6586        member
1         41.924400 -87.715400  41.9306 -87.7238        member
2         41.894500 -87.617900  41.8679 -87.6230        member
3         41.903000 -87.697500  41.8992 -87.6722        member
4         41.890200 -87.626200  41.9695 -87.6547        casual
...             ...        ...      ...      ...           ...
24828288  41.879339 -87.635700  41.9000 -87.6400        member
24828289  41.892278 -87.612043  41.8600 -87.6100        member
24828290  41.909701 -87.648408  41.9000 -87.6300        member
24828291  41.892278 -87.612043  41.8800 -87.6200        member
24828292  41.909668 -87.648128  41.9100 -87.6300        member

[24828293 rows x 13 columns]

In [10]:
display(all_data)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.896400,-87.661000,41.9322,-87.6586,member
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.924400,-87.715400,41.9306,-87.7238,member
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.894500,-87.617900,41.8679,-87.6230,member
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.903000,-87.697500,41.8992,-87.6722,member
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.890200,-87.626200,41.9695,-87.6547,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24828288,97CC940225245B6C,electric_scooter,2024-09-26 12:09:15.215,2024-09-26 12:18:48.191,Franklin St & Adams St (Temp),TA1309000008,NaN,NaN,41.879339,-87.635700,41.9000,-87.6400,member
24828289,4F8F2383056480E0,electric_bike,2024-09-10 18:10:44.046,2024-09-10 18:21:54.463,Streeter Dr & Grand Ave,13022,NaN,NaN,41.892278,-87.612043,41.8600,-87.6100,member
24828290,6A60FA5CF71D36E6,electric_bike,2024-09-14 10:52:22.777,2024-09-14 11:03:36.081,Halsted St & Clybourn Ave,331,NaN,NaN,41.909701,-87.648408,41.9000,-87.6300,member
24828291,F257ABC8B92ED5E5,electric_bike,2024-09-30 10:52:18.714,2024-09-30 11:31:46.032,Streeter Dr & Grand Ave,13022,NaN,NaN,41.892278,-87.612043,41.8800,-87.6200,member
24828292,781862ED31812AE7,electric_bike,2024-09-20 22:49:21.914,2024-09-20 23:37:15.731,Halsted St & Clybourn Ave,331,NaN,NaN,41.909668,-87.648128,41.9100,-87.6300,member